package dev.aura.updatechecker.checker;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.Value;
import org.spongepowered.api.plugin.PluginContainer;

@SuppressFBWarnings(
  value = "RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE",
  justification = "Code is generated by lombok which means I don't have any influence on it."
)
@Value
@RequiredArgsConstructor
public class DummyPluginContainer implements PluginContainer {
  private final String id;
  private final Optional<String> version;

  public DummyPluginContainer(String id) {
    this(id, Optional.empty());
  }
}
